blueprint:
  name: Ikea E1743's controlling groups of light
  description: >
    Controls a light with a switch given by ENTITY.

    Short Button press will toggle light for both Buttons (helpful in darkness)

    Mode set to restart is mandatory for stop after long press to work.
  domain: automation
  input:
    source_switch_action:
      name: Tradfri E1743 Switch
      description: The switch-action which triggers this automation.
      selector:
        entity:
          filter:
            - integration: mqtt
              domain:
                - sensor
          multiple: true
    target_light:
      name: Target Light
      description: the light you want to control.
      selector:
        target: {}
    force_brightness:
      name: Force turn on brightness
      description: >
        Force the brightness to the set level below, when the "on" button on
        the remote is pushed and lights turn on.
      default: false
      selector:
        boolean:
    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 100
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
          unit_of_measurement: "%"
    helper_transition_dim:
      name: Helper - Transition time for dimming up / down
      description: Transition time in seconds for dimming up / down. 0 makes visible steps. Greater than 0.1 makes it smoother. (0.0-10.0)
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 10.0
          mode: box
          step: 0.5
    helper_delay:
      name: Helper - Delay between each dimming step
      description: How long should be delayed between each step of dimming in milliseconds. 0 makes no delay. (10-2000)
      default: 100
      selector:
        number:
          min: 10
          max: 2000
          mode: box
          step: 10
alias: Z2M - Tradfri E1743 Switch On Off Dimming Light
description: ""
variables:
  force_brightness: !input force_brightness
trigger:
  - platform: state
    entity_id: !input source_switch_action
    id: "on"
    to: "on"
  - platform: state
    entity_id: !input source_switch_action
    id: "off"
    to: "off"
  - platform: state
    entity_id: !input source_switch_action
    id: brightness_move_up
    to: brightness_move_up
  - platform: state
    entity_id: !input source_switch_action
    id: brightness_move_down
    to: brightness_move_down
  - platform: state
    entity_id: !input source_switch_action
    id: brightness_stop
    to: brightness_stop
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ force_brightness }}"
                sequence:
                  - service: light.toggle
                    target: !input target_light
                    data:
                      brightness_pct: !input brightness
            default:
              - service: light.toggle
                target: !input target_light
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.toggle
            target: !input target_light
      - conditions:
          - condition: trigger
            id: brightness_move_up
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input source_switch_action
                  state: 'brightness_stop'
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: !input helper_transition_dim
                - delay:
                    milliseconds: !input helper_delay
      - conditions:
          - condition: trigger
            id: brightness_move_down
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input source_switch_action
                  state: 'brightness_stop'
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: !input helper_transition_dim
                - delay:
                    milliseconds: !input helper_delay
mode: restart
